import { CareerRoadmap } from "./types";

export const ROADMAP_TEMPLATES: Record<string, CareerRoadmap> = {
  "product-manager": {
    id: "template-pm",
    careerTitle: "Product Manager",
    targetLevel: "Associate / Junior",
    durationMonths: 6,
    milestones: [
      {
        id: "pm-m1",
        title: "Product Fundamentals",
        description: "Understanding the role, the product lifecycle, and market research.",
        order: 1,
        estimatedWeeks: 4,
        tasks: [
          {
            id: "pm-t1",
            title: "Role Deep Dive",
            type: "learning",
            estimatedHours: 5,
            instructions: "Research the differences between B2B, B2C, and internal product management.",
            completionCriteria: "Summarize 3 key differences in a doc.",
            status: "not_started",
          },
          {
            id: "pm-t2",
            title: "Market Analysis Exercise",
            type: "practice",
            estimatedHours: 8,
            instructions: "Pick a product and perform a SWOT analysis against its top 2 competitors.",
            completionCriteria: "Complete SWOT matrix.",
            status: "not_started",
          },
          {
            id: "pm-t3",
            title: "User Persona Creation",
            type: "practice",
            estimatedHours: 4,
            instructions: "Create 2 detailed user personas for a new food delivery app.",
            completionCriteria: "Two persona profiles with goals and pain points.",
            status: "not_started",
          },
        ],
      },
      {
        id: "pm-m2",
        title: "Discovery & Strategy",
        description: "User interviews, problem identification, and prioritization.",
        order: 2,
        estimatedWeeks: 6,
        tasks: [
          {
            id: "pm-t4",
            title: "User Interview Guide",
            type: "practice",
            estimatedHours: 6,
            instructions: "Draft 10 open-ended questions for a specific user persona.",
            completionCriteria: "List of 10 questions ready for use.",
            status: "not_started",
          },
          {
            id: "pm-t5",
            title: "Problem Statement Framing",
            type: "practice",
            estimatedHours: 3,
            instructions: "Write 3 'How Might We' statements based on user pain points.",
            completionCriteria: "3 HMW statements.",
            status: "not_started",
          },
          {
            id: "pm-t6",
            title: "Feature Prioritization",
            type: "practice",
            estimatedHours: 5,
            instructions: "Use the RICE framework to prioritize 5 features for a fitness app.",
            completionCriteria: "Ranked list of features with RICE scores.",
            status: "not_started",
          },
        ],
      },
      {
        id: "pm-m3",
        title: "Execution & Metrics",
        description: "Writing specs, working with engineering, and tracking success.",
        order: 3,
        estimatedWeeks: 6,
        tasks: [
          {
            id: "pm-t7",
            title: "PRD Drafting",
            type: "practice",
            estimatedHours: 10,
            instructions: "Write a Product Requirements Document (PRD) for a small feature (e.g., 'Save for Later').",
            completionCriteria: "Completed PRD with user stories and acceptance criteria.",
            status: "not_started",
          },
          {
            id: "pm-t8",
            title: "KPI Definition",
            type: "learning",
            estimatedHours: 4,
            instructions: "Define 3 success metrics (KPIs) for the feature drafted in the PRD.",
            completionCriteria: "List of 3 metrics with measurement methods.",
            status: "not_started",
          },
        ],
      },
    ],
  },
  "ux-designer": {
    id: "template-ux",
    careerTitle: "UX Designer",
    targetLevel: "Junior",
    durationMonths: 6,
    milestones: [
      {
        id: "ux-m1",
        title: "Design Foundations",
        description: "Mastering layout, typography, and color theory.",
        order: 1,
        estimatedWeeks: 4,
        tasks: [
          {
            id: "ux-t1",
            title: "Visual Hierarchy Study",
            type: "learning",
            estimatedHours: 6,
            instructions: "Study principles of visual hierarchy: size, color, contrast, and alignment.",
            completionCriteria: "Analyze 3 apps and point out their hierarchy choices.",
            status: "not_started",
          },
          {
            id: "ux-t2",
            title: "Typography Exercise",
            type: "practice",
            estimatedHours: 5,
            instructions: "Create a typography scale for a mobile app project.",
            completionCriteria: "Scale with H1, H2, Body, and Caption styles.",
            status: "not_started",
          },
        ],
      },
      {
        id: "ux-m2",
        title: "Wireframing & Prototyping",
        description: "Translating ideas into low and high fidelity designs.",
        order: 2,
        estimatedWeeks: 8,
        tasks: [
          {
            id: "ux-t3",
            title: "Lo-Fi Sketching",
            type: "practice",
            estimatedHours: 4,
            instructions: "Sketch 5 different layouts for a landing page on paper.",
            completionCriteria: "5 scanned or photographed sketches.",
            status: "not_started",
          },
          {
            id: "ux-t4",
            title: "Hi-Fi Prototyping in Figma",
            type: "practice",
            estimatedHours: 12,
            instructions: "Create an interactive prototype for a 3-screen flow (Login, Dashboard, Profile).",
            completionCriteria: "Link to a clickable Figma prototype.",
            status: "not_started",
          },
        ],
      },
      {
        id: "ux-m3",
        title: "Usability & Handoff",
        description: "Testing designs and preparing for development.",
        order: 3,
        estimatedWeeks: 4,
        tasks: [
          {
            id: "ux-t5",
            title: "Conducting Usability Tests",
            type: "practice",
            estimatedHours: 8,
            instructions: "Test your prototype with 3 users and record pain points.",
            completionCriteria: "Summary report of findings and 2 suggested fixes.",
            status: "not_started",
          },
        ],
      },
    ],
  },
  "software-developer": {
    id: "template-sd",
    careerTitle: "Software Developer",
    targetLevel: "Junior Fullstack",
    durationMonths: 8,
    milestones: [
      {
        id: "sd-m1",
        title: "Frontend Mastery",
        description: "React, CSS, and responsive design foundations.",
        order: 1,
        estimatedWeeks: 6,
        tasks: [
          {
            id: "sd-t1",
            title: "React Components & Hooks",
            type: "learning",
            estimatedHours: 15,
            instructions: "Build a functional Todo app using useState and useEffect.",
            completionCriteria: "Working Todo app with add/delete functionality.",
            status: "not_started",
          },
          {
            id: "sd-t2",
            title: "Tailwind CSS Layouts",
            type: "practice",
            estimatedHours: 8,
            instructions: "Recreate a complex dashboard layout using only Tailwind utility classes.",
            completionCriteria: "Pixel-perfect responsive layout.",
            status: "not_started",
          },
        ],
      },
      {
        id: "sd-m2",
        title: "Backend & Databases",
        description: "Node.js, APIs, and relational databases.",
        order: 2,
        estimatedWeeks: 8,
        tasks: [
          {
            id: "sd-t3",
            title: "REST API Development",
            type: "practice",
            estimatedHours: 12,
            instructions: "Create a Express.js server with CRUD endpoints for a 'Books' collection.",
            completionCriteria: "API tested and working in Postman.",
            status: "not_started",
          },
          {
            id: "sd-t4",
            title: "SQL Schema Design",
            type: "practice",
            estimatedHours: 6,
            instructions: "Design a database schema for an e-commerce platform (Users, Products, Orders).",
            completionCriteria: "ER diagram or SQL DDL script.",
            status: "not_started",
          },
        ],
      },
    ],
  },
  "data-analyst": {
    id: "template-da",
    careerTitle: "Data Analyst",
    targetLevel: "Entry Level",
    durationMonths: 6,
    milestones: [
      {
        id: "da-m1",
        title: "Data Querying & SQL",
        description: "Mastering SQL for data extraction and manipulation.",
        order: 1,
        estimatedWeeks: 6,
        tasks: [
          {
            id: "da-t1",
            title: "Advanced Joins & CTEs",
            type: "learning",
            estimatedHours: 10,
            instructions: "Learn to use Common Table Expressions (CTEs) and multiple joins.",
            completionCriteria: "Solve 5 complex query challenges on a dataset.",
            status: "not_started",
          },
        ],
      },
      {
        id: "da-m2",
        title: "Visualization & Storytelling",
        description: "Creating dashboards and communicating insights.",
        order: 2,
        estimatedWeeks: 6,
        tasks: [
          {
            id: "da-t2",
            title: "Tableau/PowerBI Dashboard",
            type: "practice",
            estimatedHours: 12,
            instructions: "Build a sales performance dashboard with at least 4 different chart types.",
            completionCriteria: "Interactive dashboard file or screenshot.",
            status: "not_started",
          },
        ],
      },
    ],
  },
  "digital-marketer": {
    id: "template-dm",
    careerTitle: "Digital Marketer",
    targetLevel: "Junior",
    durationMonths: 5,
    milestones: [
      {
        id: "dm-m1",
        title: "Content & SEO",
        description: "Optimizing for search and creating engaging content.",
        order: 1,
        estimatedWeeks: 5,
        tasks: [
          {
            id: "dm-t1",
            title: "Keyword Research",
            type: "practice",
            estimatedHours: 6,
            instructions: "Find 20 high-volume, low-competition keywords for a niche blog.",
            completionCriteria: "Spreadsheet with keywords, volume, and difficulty.",
            status: "not_started",
          },
        ],
      },
      {
        id: "dm-m2",
        title: "Paid Media & Analytics",
        description: "Managing ads and tracking performance.",
        order: 2,
        estimatedWeeks: 6,
        tasks: [
          {
            id: "dm-t2",
            title: "Google Ads Campaign Setup",
            type: "practice",
            estimatedHours: 8,
            instructions: "Draft an ad group with 3 different ad copies and target audiences.",
            completionCriteria: "Completed campaign plan document.",
            status: "not_started",
          },
        ],
      },
    ],
  },
  "ux-researcher": {
    id: "template-uxr",
    careerTitle: "UX Researcher",
    targetLevel: "Junior",
    durationMonths: 6,
    milestones: [
      {
        id: "uxr-m1",
        title: "Research Planning",
        description: "Defining objectives and choosing methodologies.",
        order: 1,
        estimatedWeeks: 4,
        tasks: [
          {
            id: "uxr-t1",
            title: "Research Plan Drafting",
            type: "practice",
            estimatedHours: 6,
            instructions: "Write a research plan for investigating why users drop off during checkout.",
            completionCriteria: "Plan covering goals, participants, and methods.",
            status: "not_started",
          },
        ],
      },
      {
        id: "uxr-m2",
        title: "Execution & Analysis",
        description: "Conducting studies and synthesizing findings.",
        order: 2,
        estimatedWeeks: 8,
        tasks: [
          {
            id: "uxr-t2",
            title: "Affinity Mapping",
            type: "practice",
            estimatedHours: 5,
            instructions: "Synthesize 10 user interview notes into themes using FigJam or Miro.",
            completionCriteria: "Affinity map with at least 4 key themes identified.",
            status: "not_started",
          },
        ],
      },
    ],
  },
  "business-analyst": {
    id: "template-ba",
    careerTitle: "Business Analyst",
    targetLevel: "Entry Level",
    durationMonths: 5,
    milestones: [
      {
        id: "ba-m1",
        title: "Requirements Gathering",
        description: "Interviewing stakeholders and documenting needs.",
        order: 1,
        estimatedWeeks: 5,
        tasks: [
          {
            id: "ba-t1",
            title: "Stakeholder Map",
            type: "practice",
            estimatedHours: 4,
            instructions: "Create a Power/Interest grid for a new internal CRM project.",
            completionCriteria: "Grid with at least 5 stakeholders mapped.",
            status: "not_started",
          },
        ],
      },
      {
        id: "ba-m2",
        title: "Data & Process Analysis",
        description: "Analyzing business data and mapping workflows.",
        order: 2,
        estimatedWeeks: 6,
        tasks: [
          {
            id: "ba-t2",
            title: "Gap Analysis",
            type: "practice",
            estimatedHours: 8,
            instructions: "Perform a gap analysis between current and future state of a billing process.",
            completionCriteria: "Report highlighting 3 major gaps and recommendations.",
            status: "not_started",
          },
        ],
      },
    ],
  },
  "content-strategist": {
    id: "template-cs",
    careerTitle: "Content Strategist",
    targetLevel: "Junior",
    durationMonths: 4,
    milestones: [
      {
        id: "cs-m1",
        title: "Content Strategy Foundations",
        description: "Auditing content and defining governance.",
        order: 1,
        estimatedWeeks: 4,
        tasks: [
          {
            id: "cs-t1",
            title: "Content Audit",
            type: "practice",
            estimatedHours: 10,
            instructions: "Audit 10 pages of a website for accuracy, tone, and SEO.",
            completionCriteria: "Audit spreadsheet with action items (Keep, Update, Delete).",
            status: "not_started",
          },
        ],
      },
      {
        id: "cs-m2",
        title: "Editorial Planning",
        description: "Creating calendars and managing content production.",
        order: 2,
        estimatedWeeks: 6,
        tasks: [
          {
            id: "cs-t2",
            title: "Editorial Calendar",
            type: "practice",
            estimatedHours: 6,
            instructions: "Build a 1-month editorial calendar for a tech blog.",
            completionCriteria: "Calendar with 8 topics, formats, and target dates.",
            status: "not_started",
          },
        ],
      },
    ],
  },
  "fallback": {
    id: "template-fallback",
    careerTitle: "Professional Explorer",
    targetLevel: "Foundational",
    durationMonths: 3,
    milestones: [
      {
        id: "fb-m1",
        title: "Self-Discovery & Market Scan",
        description: "Identifying interests and researching industries.",
        order: 1,
        estimatedWeeks: 4,
        tasks: [
          {
            id: "fb-t1",
            title: "Informational Interview",
            type: "practice",
            estimatedHours: 4,
            instructions: "Reach out to one person in a field of interest for a 15-min chat.",
            completionCriteria: "Notes from the conversation.",
            status: "not_started",
          },
        ],
      },
    ],
  },
};
