import type { AssessmentQuestion } from "./types";

export const seedQuestions: AssessmentQuestion[] = [
  {
    id: "seed-01",
    text: "When you face a new challenge, what do you naturally do first?",
    category: "problem_solving",
    difficultyLevel: 1,
    followUpTags: ["analytical_thinking", "creative_expression", "people_orientation", "structured_thinking"],
    isSeed: true,
    options: [
      { key: "A", text: "Break it into smaller parts", traitEffects: { analytical_thinking: 3, structured_thinking: 2 } },
      { key: "B", text: "Imagine a few fresh ways to solve it", traitEffects: { creative_expression: 3, curiosity: 1 } },
      { key: "C", text: "Ask people what they need from the solution", traitEffects: { people_orientation: 2, empathy: 2 } },
      { key: "D", text: "Create a step-by-step plan", traitEffects: { execution_discipline: 2, structured_thinking: 3 } },
    ],
  },
  {
    id: "seed-02",
    text: "Which project role feels most comfortable to you?",
    category: "collaboration",
    difficultyLevel: 1,
    followUpTags: ["leadership_drive", "execution_discipline", "communication_strength", "detail_orientation"],
    isSeed: true,
    options: [
      { key: "A", text: "Setting direction and keeping momentum", traitEffects: { leadership_drive: 3, communication_strength: 1 } },
      { key: "B", text: "Making sure details are correct", traitEffects: { detail_orientation: 3, execution_discipline: 1 } },
      { key: "C", text: "Helping everyone stay aligned", traitEffects: { communication_strength: 2, people_orientation: 2 } },
      { key: "D", text: "Quietly finishing the important work", traitEffects: { execution_discipline: 3, autonomy_preference: 1 } },
    ],
  },
  {
    id: "seed-03",
    text: "What kind of task gives you energy?",
    category: "values",
    difficultyLevel: 1,
    followUpTags: ["technical_curiosity", "learning_agility", "creative_expression", "empathy"],
    isSeed: true,
    options: [
      { key: "A", text: "Learning a new tool or system", traitEffects: { learning_agility: 2, technical_curiosity: 2 } },
      { key: "B", text: "Designing something expressive", traitEffects: { creative_expression: 3, curiosity: 1 } },
      { key: "C", text: "Understanding why people behave a certain way", traitEffects: { empathy: 3, curiosity: 1 } },
      { key: "D", text: "Turning ideas into measurable results", traitEffects: { execution_discipline: 2, analytical_thinking: 2 } },
    ],
  },
  {
    id: "seed-04",
    text: "How do you prefer to make decisions?",
    category: "problem_solving",
    difficultyLevel: 1,
    followUpTags: ["analytical_thinking", "risk_appetite", "empathy", "structured_thinking"],
    isSeed: true,
    options: [
      { key: "A", text: "Use data and compare options", traitEffects: { analytical_thinking: 3, detail_orientation: 1 } },
      { key: "B", text: "Move quickly and learn from outcomes", traitEffects: { risk_appetite: 3, learning_agility: 1 } },
      { key: "C", text: "Consider how people will feel", traitEffects: { empathy: 3, people_orientation: 1 } },
      { key: "D", text: "Follow a clear decision framework", traitEffects: { structured_thinking: 3, execution_discipline: 1 } },
    ],
  },
  {
    id: "seed-05",
    text: "In a team discussion, what do you usually notice?",
    category: "communication",
    difficultyLevel: 1,
    followUpTags: ["communication_strength", "empathy", "leadership_drive", "detail_orientation"],
    isSeed: true,
    options: [
      { key: "A", text: "Where the conversation lacks clarity", traitEffects: { communication_strength: 3, structured_thinking: 1 } },
      { key: "B", text: "Who has not been heard yet", traitEffects: { empathy: 3, people_orientation: 1 } },
      { key: "C", text: "What decision needs to be made", traitEffects: { leadership_drive: 2, execution_discipline: 2 } },
      { key: "D", text: "Which facts still need checking", traitEffects: { detail_orientation: 3, analytical_thinking: 1 } },
    ],
  },
  {
    id: "seed-06",
    text: "Which learning path sounds best?",
    category: "learning",
    difficultyLevel: 1,
    followUpTags: ["learning_agility", "technical_curiosity", "structured_thinking", "autonomy_preference"],
    isSeed: true,
    options: [
      { key: "A", text: "Experiment, fail, and improve", traitEffects: { learning_agility: 3, risk_appetite: 1 } },
      { key: "B", text: "Understand the technical mechanics", traitEffects: { technical_curiosity: 3, analytical_thinking: 1 } },
      { key: "C", text: "Follow a structured curriculum", traitEffects: { structured_thinking: 2, execution_discipline: 2 } },
      { key: "D", text: "Explore independently at my pace", traitEffects: { autonomy_preference: 3, curiosity: 1 } },
    ],
  },
  {
    id: "seed-07",
    text: "What frustrates you most in work?",
    category: "work_style",
    difficultyLevel: 1,
    followUpTags: ["autonomy_preference", "detail_orientation", "execution_discipline", "communication_strength"],
    isSeed: true,
    options: [
      { key: "A", text: "Too much micromanagement", traitEffects: { autonomy_preference: 3, leadership_drive: 1 } },
      { key: "B", text: "Sloppy or incomplete work", traitEffects: { detail_orientation: 3, execution_discipline: 1 } },
      { key: "C", text: "Endless talk without progress", traitEffects: { execution_discipline: 3, structured_thinking: 1 } },
      { key: "D", text: "Unclear expectations", traitEffects: { communication_strength: 2, structured_thinking: 2 } },
    ],
  },
  {
    id: "seed-08",
    text: "Pick the challenge you would rather solve.",
    category: "technology",
    difficultyLevel: 1,
    followUpTags: ["technical_curiosity", "creative_expression", "people_orientation", "analytical_thinking"],
    isSeed: true,
    options: [
      { key: "A", text: "Build a simple digital prototype", traitEffects: { technical_curiosity: 3, execution_discipline: 1 } },
      { key: "B", text: "Create a visual identity for a product", traitEffects: { creative_expression: 3, detail_orientation: 1 } },
      { key: "C", text: "Interview people about a problem", traitEffects: { people_orientation: 2, empathy: 2 } },
      { key: "D", text: "Analyze why a metric changed", traitEffects: { analytical_thinking: 3, curiosity: 1 } },
    ],
  },
  {
    id: "seed-09",
    text: "How do you respond to uncertainty?",
    category: "work_style",
    difficultyLevel: 1,
    followUpTags: ["risk_appetite", "structured_thinking", "curiosity", "leadership_drive"],
    isSeed: true,
    options: [
      { key: "A", text: "Try a small bet and learn", traitEffects: { risk_appetite: 3, learning_agility: 1 } },
      { key: "B", text: "Create structure before acting", traitEffects: { structured_thinking: 3, detail_orientation: 1 } },
      { key: "C", text: "Ask more questions", traitEffects: { curiosity: 3, communication_strength: 1 } },
      { key: "D", text: "Help others move through it", traitEffects: { leadership_drive: 2, empathy: 2 } },
    ],
  },
  {
    id: "seed-10",
    text: "What result would make you proudest?",
    category: "values",
    difficultyLevel: 1,
    followUpTags: ["execution_discipline", "creative_expression", "people_orientation", "technical_curiosity"],
    isSeed: true,
    options: [
      { key: "A", text: "Shipping something useful", traitEffects: { execution_discipline: 3, technical_curiosity: 1 } },
      { key: "B", text: "Making something memorable", traitEffects: { creative_expression: 3, communication_strength: 1 } },
      { key: "C", text: "Helping someone feel understood", traitEffects: { people_orientation: 2, empathy: 2 } },
      { key: "D", text: "Mastering a complex skill", traitEffects: { technical_curiosity: 2, learning_agility: 2 } },
    ],
  },
];

export const adaptiveQuestions: AssessmentQuestion[] = [
  {
    id: "adaptive-01",
    text: "When comparing two ideas, what matters most?",
    category: "problem_solving",
    difficultyLevel: 2,
    followUpTags: ["analytical_thinking", "structured_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Evidence that one is more likely to work", traitEffects: { analytical_thinking: 3 } },
      { key: "B", text: "Which one feels more original", traitEffects: { creative_expression: 3 } },
      { key: "C", text: "Which one helps people faster", traitEffects: { empathy: 2, execution_discipline: 1 } },
      { key: "D", text: "Which one can be organized clearly", traitEffects: { structured_thinking: 3 } },
    ],
  },
  {
    id: "adaptive-02",
    text: "You notice a product is confusing. What do you investigate first?",
    category: "problem_solving",
    difficultyLevel: 2,
    followUpTags: ["empathy", "analytical_thinking", "detail_orientation"],
    isSeed: false,
    options: [
      { key: "A", text: "Where users hesitate or get stuck", traitEffects: { empathy: 2, analytical_thinking: 1 } },
      { key: "B", text: "The labels, spacing, and small details", traitEffects: { detail_orientation: 3 } },
      { key: "C", text: "Whether the flow has a clear structure", traitEffects: { structured_thinking: 3 } },
      { key: "D", text: "How competitors solve the same thing", traitEffects: { curiosity: 2, analytical_thinking: 1 } },
    ],
  },
  {
    id: "adaptive-03",
    text: "Which kind of ambiguity feels most manageable?",
    category: "work_style",
    difficultyLevel: 2,
    followUpTags: ["risk_appetite", "learning_agility", "autonomy_preference"],
    isSeed: false,
    options: [
      { key: "A", text: "No clear answer yet, but experiments are possible", traitEffects: { risk_appetite: 2, learning_agility: 2 } },
      { key: "B", text: "No manager nearby, but I can decide", traitEffects: { autonomy_preference: 3 } },
      { key: "C", text: "No process yet, but I can create one", traitEffects: { structured_thinking: 2, leadership_drive: 1 } },
      { key: "D", text: "No user clarity yet, but I can ask people", traitEffects: { empathy: 2, communication_strength: 1 } },
    ],
  },
  {
    id: "adaptive-04",
    text: "Which detail do you care about most before launch?",
    category: "execution",
    difficultyLevel: 2,
    followUpTags: ["detail_orientation", "execution_discipline"],
    isSeed: false,
    options: [
      { key: "A", text: "The experience has no obvious friction", traitEffects: { detail_orientation: 2, empathy: 1 } },
      { key: "B", text: "The system works reliably", traitEffects: { technical_curiosity: 2, detail_orientation: 1 } },
      { key: "C", text: "The team knows the plan", traitEffects: { communication_strength: 2, execution_discipline: 1 } },
      { key: "D", text: "The next steps are ready", traitEffects: { execution_discipline: 3 } },
    ],
  },
  {
    id: "adaptive-05",
    text: "A teammate disagrees with your idea. What do you do?",
    category: "collaboration",
    difficultyLevel: 2,
    followUpTags: ["communication_strength", "empathy", "leadership_drive"],
    isSeed: false,
    options: [
      { key: "A", text: "Ask what concern sits behind their disagreement", traitEffects: { empathy: 2, communication_strength: 2 } },
      { key: "B", text: "Suggest a quick test to compare options", traitEffects: { analytical_thinking: 2, risk_appetite: 1 } },
      { key: "C", text: "Clarify the decision criteria", traitEffects: { structured_thinking: 2, leadership_drive: 1 } },
      { key: "D", text: "Revise the idea if their point is strong", traitEffects: { learning_agility: 2, empathy: 1 } },
    ],
  },
  {
    id: "adaptive-06",
    text: "Which creative task sounds most natural?",
    category: "creativity",
    difficultyLevel: 2,
    followUpTags: ["creative_expression", "communication_strength"],
    isSeed: false,
    options: [
      { key: "A", text: "Naming and shaping a concept", traitEffects: { creative_expression: 3 } },
      { key: "B", text: "Making a message more persuasive", traitEffects: { communication_strength: 2, creative_expression: 1 } },
      { key: "C", text: "Designing a clean process", traitEffects: { structured_thinking: 2, detail_orientation: 1 } },
      { key: "D", text: "Finding unusual patterns in data", traitEffects: { analytical_thinking: 2, curiosity: 1 } },
    ],
  },
  {
    id: "adaptive-07",
    text: "How do you prefer to own work?",
    category: "work_style",
    difficultyLevel: 2,
    followUpTags: ["autonomy_preference", "execution_discipline"],
    isSeed: false,
    options: [
      { key: "A", text: "Give me the outcome and room to decide", traitEffects: { autonomy_preference: 3, execution_discipline: 1 } },
      { key: "B", text: "Give me a clear brief and checkpoints", traitEffects: { structured_thinking: 2, communication_strength: 1 } },
      { key: "C", text: "Let me coordinate the group", traitEffects: { leadership_drive: 3 } },
      { key: "D", text: "Let me focus deeply on one piece", traitEffects: { detail_orientation: 2, autonomy_preference: 1 } },
    ],
  },
  {
    id: "adaptive-08",
    text: "Which technical topic would you explore first?",
    category: "technology",
    difficultyLevel: 2,
    followUpTags: ["technical_curiosity", "learning_agility"],
    isSeed: false,
    options: [
      { key: "A", text: "How apps store and retrieve data", traitEffects: { technical_curiosity: 3 } },
      { key: "B", text: "How interfaces guide behavior", traitEffects: { empathy: 1, curiosity: 2 } },
      { key: "C", text: "How analytics reveal usage patterns", traitEffects: { analytical_thinking: 2, technical_curiosity: 1 } },
      { key: "D", text: "How automation speeds up work", traitEffects: { execution_discipline: 2, technical_curiosity: 1 } },
    ],
  },
  {
    id: "adaptive-09",
    text: "What makes you trust a conclusion?",
    category: "problem_solving",
    difficultyLevel: 2,
    followUpTags: ["analytical_thinking", "detail_orientation"],
    isSeed: false,
    options: [
      { key: "A", text: "Clear data and assumptions", traitEffects: { analytical_thinking: 3, detail_orientation: 1 } },
      { key: "B", text: "Repeated user feedback", traitEffects: { empathy: 2, analytical_thinking: 1 } },
      { key: "C", text: "A simple explanation others understand", traitEffects: { communication_strength: 3 } },
      { key: "D", text: "A practical test in the real world", traitEffects: { risk_appetite: 2, execution_discipline: 1 } },
    ],
  },
  {
    id: "adaptive-10",
    text: "Which leadership moment feels energizing?",
    category: "leadership",
    difficultyLevel: 2,
    followUpTags: ["leadership_drive", "people_orientation"],
    isSeed: false,
    options: [
      { key: "A", text: "Setting a direction when people are unsure", traitEffects: { leadership_drive: 3 } },
      { key: "B", text: "Helping someone perform better", traitEffects: { people_orientation: 2, empathy: 1 } },
      { key: "C", text: "Making a tough priority call", traitEffects: { leadership_drive: 2, structured_thinking: 1 } },
      { key: "D", text: "Keeping the team accountable", traitEffects: { execution_discipline: 2, communication_strength: 1 } },
    ],
  },
  {
    id: "adaptive-11",
    text: "When improving a workflow, where do you begin?",
    category: "execution",
    difficultyLevel: 2,
    followUpTags: ["structured_thinking", "execution_discipline"],
    isSeed: false,
    options: [
      { key: "A", text: "Map the current steps", traitEffects: { structured_thinking: 3 } },
      { key: "B", text: "Find the slowest part", traitEffects: { analytical_thinking: 2, execution_discipline: 1 } },
      { key: "C", text: "Ask people what feels painful", traitEffects: { empathy: 2, communication_strength: 1 } },
      { key: "D", text: "Try a faster version immediately", traitEffects: { risk_appetite: 2, execution_discipline: 1 } },
    ],
  },
  {
    id: "adaptive-12",
    text: "Which research activity would you choose?",
    category: "learning",
    difficultyLevel: 2,
    followUpTags: ["curiosity", "empathy", "analytical_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Interview people one-on-one", traitEffects: { empathy: 3, curiosity: 1 } },
      { key: "B", text: "Analyze patterns across responses", traitEffects: { analytical_thinking: 3 } },
      { key: "C", text: "Read widely across related topics", traitEffects: { curiosity: 3 } },
      { key: "D", text: "Turn findings into a concise brief", traitEffects: { communication_strength: 2, structured_thinking: 1 } },
    ],
  },
  {
    id: "adaptive-13",
    text: "How do you handle repetitive tasks?",
    category: "execution",
    difficultyLevel: 2,
    followUpTags: ["execution_discipline", "technical_curiosity", "detail_orientation"],
    isSeed: false,
    options: [
      { key: "A", text: "Create a checklist and finish steadily", traitEffects: { execution_discipline: 3, detail_orientation: 1 } },
      { key: "B", text: "Look for a way to automate them", traitEffects: { technical_curiosity: 2, execution_discipline: 1 } },
      { key: "C", text: "Improve the process so it is less boring", traitEffects: { creative_expression: 2, structured_thinking: 1 } },
      { key: "D", text: "Batch them and protect focus time", traitEffects: { autonomy_preference: 2, execution_discipline: 1 } },
    ],
  },
  {
    id: "adaptive-14",
    text: "Which feedback is most useful to you?",
    category: "learning",
    difficultyLevel: 2,
    followUpTags: ["learning_agility", "detail_orientation", "communication_strength"],
    isSeed: false,
    options: [
      { key: "A", text: "Specific examples of what to improve", traitEffects: { learning_agility: 2, detail_orientation: 2 } },
      { key: "B", text: "A high-level direction and trust", traitEffects: { autonomy_preference: 3 } },
      { key: "C", text: "Honest discussion about impact", traitEffects: { communication_strength: 2, empathy: 1 } },
      { key: "D", text: "Metrics showing what changed", traitEffects: { analytical_thinking: 3 } },
    ],
  },
  {
    id: "adaptive-15",
    text: "What would you rather present?",
    category: "communication",
    difficultyLevel: 2,
    followUpTags: ["communication_strength", "creative_expression", "analytical_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "A data-backed recommendation", traitEffects: { analytical_thinking: 2, communication_strength: 1 } },
      { key: "B", text: "A compelling product story", traitEffects: { creative_expression: 2, communication_strength: 2 } },
      { key: "C", text: "A team plan with owners", traitEffects: { leadership_drive: 1, execution_discipline: 2 } },
      { key: "D", text: "A user insight summary", traitEffects: { empathy: 2, communication_strength: 1 } },
    ],
  },
  {
    id: "adaptive-16",
    text: "What kind of risk feels worth taking?",
    category: "values",
    difficultyLevel: 2,
    followUpTags: ["risk_appetite", "creative_expression"],
    isSeed: false,
    options: [
      { key: "A", text: "Trying a new idea before it is proven", traitEffects: { risk_appetite: 3, creative_expression: 1 } },
      { key: "B", text: "Choosing a hard technical path", traitEffects: { technical_curiosity: 2, risk_appetite: 1 } },
      { key: "C", text: "Challenging a weak team decision", traitEffects: { leadership_drive: 2, communication_strength: 1 } },
      { key: "D", text: "Spending time deeply understanding people", traitEffects: { empathy: 2, curiosity: 1 } },
    ],
  },
  {
    id: "adaptive-17",
    text: "Which signal tells you a product is good?",
    category: "problem_solving",
    difficultyLevel: 2,
    followUpTags: ["empathy", "analytical_thinking", "detail_orientation"],
    isSeed: false,
    options: [
      { key: "A", text: "People can use it without explanation", traitEffects: { empathy: 2, detail_orientation: 1 } },
      { key: "B", text: "The numbers improve after launch", traitEffects: { analytical_thinking: 3 } },
      { key: "C", text: "The design feels distinctive", traitEffects: { creative_expression: 3 } },
      { key: "D", text: "The team can maintain it well", traitEffects: { structured_thinking: 2, technical_curiosity: 1 } },
    ],
  },
  {
    id: "adaptive-18",
    text: "How do you prefer to explore an unfamiliar domain?",
    category: "learning",
    difficultyLevel: 2,
    followUpTags: ["curiosity", "learning_agility", "structured_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Ask broad questions and follow interesting leads", traitEffects: { curiosity: 3 } },
      { key: "B", text: "Build a small project to learn by doing", traitEffects: { learning_agility: 2, technical_curiosity: 1 } },
      { key: "C", text: "Create a learning plan", traitEffects: { structured_thinking: 2, execution_discipline: 1 } },
      { key: "D", text: "Talk to experienced people", traitEffects: { people_orientation: 2, communication_strength: 1 } },
    ],
  },
  {
    id: "adaptive-19",
    text: "What do you do when a deadline is close?",
    category: "execution",
    difficultyLevel: 2,
    followUpTags: ["execution_discipline", "leadership_drive", "structured_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Prioritize ruthlessly", traitEffects: { structured_thinking: 2, execution_discipline: 2 } },
      { key: "B", text: "Rally people around the goal", traitEffects: { leadership_drive: 2, communication_strength: 1 } },
      { key: "C", text: "Focus on the details that could break", traitEffects: { detail_orientation: 3 } },
      { key: "D", text: "Ship a useful version and iterate", traitEffects: { risk_appetite: 2, execution_discipline: 1 } },
    ],
  },
  {
    id: "adaptive-20",
    text: "Which environment helps you do your best work?",
    category: "work_style",
    difficultyLevel: 2,
    followUpTags: ["autonomy_preference", "people_orientation", "structured_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Independent ownership with clear goals", traitEffects: { autonomy_preference: 3, execution_discipline: 1 } },
      { key: "B", text: "A collaborative team with open conversation", traitEffects: { people_orientation: 2, communication_strength: 2 } },
      { key: "C", text: "A structured process with predictable rhythms", traitEffects: { structured_thinking: 3 } },
      { key: "D", text: "A fast-moving space with room to experiment", traitEffects: { risk_appetite: 2, learning_agility: 1 } },
    ],
  },
  {
    id: "adaptive-21",
    text: "What would you optimize in a messy dashboard?",
    category: "technology",
    difficultyLevel: 3,
    followUpTags: ["analytical_thinking", "detail_orientation", "communication_strength"],
    isSeed: false,
    options: [
      { key: "A", text: "The most important metrics", traitEffects: { analytical_thinking: 3 } },
      { key: "B", text: "The visual hierarchy", traitEffects: { detail_orientation: 2, creative_expression: 1 } },
      { key: "C", text: "The story it tells a decision-maker", traitEffects: { communication_strength: 3 } },
      { key: "D", text: "The data source reliability", traitEffects: { technical_curiosity: 2, detail_orientation: 1 } },
    ],
  },
  {
    id: "adaptive-22",
    text: "Which planning method feels most useful?",
    category: "execution",
    difficultyLevel: 2,
    followUpTags: ["structured_thinking", "execution_discipline"],
    isSeed: false,
    options: [
      { key: "A", text: "Milestones and owners", traitEffects: { execution_discipline: 2, leadership_drive: 1 } },
      { key: "B", text: "Decision trees and criteria", traitEffects: { structured_thinking: 3 } },
      { key: "C", text: "Experiments and checkpoints", traitEffects: { risk_appetite: 1, learning_agility: 2 } },
      { key: "D", text: "User journeys and pain points", traitEffects: { empathy: 2, structured_thinking: 1 } },
    ],
  },
  {
    id: "adaptive-23",
    text: "How do you prefer to solve people problems?",
    category: "collaboration",
    difficultyLevel: 2,
    followUpTags: ["empathy", "people_orientation", "communication_strength"],
    isSeed: false,
    options: [
      { key: "A", text: "Listen for what is not being said", traitEffects: { empathy: 3 } },
      { key: "B", text: "Bring people into a shared conversation", traitEffects: { people_orientation: 2, communication_strength: 2 } },
      { key: "C", text: "Clarify roles and expectations", traitEffects: { structured_thinking: 2, communication_strength: 1 } },
      { key: "D", text: "Make the tough call if needed", traitEffects: { leadership_drive: 3 } },
    ],
  },
  {
    id: "adaptive-24",
    text: "Which builder instinct is strongest?",
    category: "technology",
    difficultyLevel: 2,
    followUpTags: ["technical_curiosity", "execution_discipline", "creative_expression"],
    isSeed: false,
    options: [
      { key: "A", text: "Make it function", traitEffects: { technical_curiosity: 2, execution_discipline: 1 } },
      { key: "B", text: "Make it elegant", traitEffects: { creative_expression: 2, detail_orientation: 1 } },
      { key: "C", text: "Make it understandable", traitEffects: { communication_strength: 2, empathy: 1 } },
      { key: "D", text: "Make it scalable", traitEffects: { structured_thinking: 2, technical_curiosity: 1 } },
    ],
  },
  {
    id: "adaptive-25",
    text: "What kind of curiosity pulls you in?",
    category: "learning",
    difficultyLevel: 2,
    followUpTags: ["curiosity", "technical_curiosity", "people_orientation"],
    isSeed: false,
    options: [
      { key: "A", text: "Why systems work the way they do", traitEffects: { technical_curiosity: 2, curiosity: 2 } },
      { key: "B", text: "Why people choose what they choose", traitEffects: { empathy: 2, curiosity: 2 } },
      { key: "C", text: "Why some ideas spread", traitEffects: { communication_strength: 2, curiosity: 1 } },
      { key: "D", text: "Why some teams execute better", traitEffects: { execution_discipline: 2, curiosity: 1 } },
    ],
  },
  {
    id: "adaptive-26",
    text: "What makes a goal motivating?",
    category: "values",
    difficultyLevel: 2,
    followUpTags: ["leadership_drive", "autonomy_preference", "people_orientation", "learning_agility"],
    isSeed: false,
    options: [
      { key: "A", text: "It gives me ownership", traitEffects: { autonomy_preference: 3 } },
      { key: "B", text: "It helps people meaningfully", traitEffects: { people_orientation: 2, empathy: 1 } },
      { key: "C", text: "It stretches my ability", traitEffects: { learning_agility: 3 } },
      { key: "D", text: "It lets me lead change", traitEffects: { leadership_drive: 3 } },
    ],
  },
  {
    id: "adaptive-27",
    text: "If a plan fails, what do you review first?",
    category: "execution",
    difficultyLevel: 3,
    followUpTags: ["analytical_thinking", "execution_discipline", "learning_agility"],
    isSeed: false,
    options: [
      { key: "A", text: "Which assumption was wrong", traitEffects: { analytical_thinking: 2, learning_agility: 1 } },
      { key: "B", text: "Where execution slipped", traitEffects: { execution_discipline: 3 } },
      { key: "C", text: "Whether people understood the goal", traitEffects: { communication_strength: 2, leadership_drive: 1 } },
      { key: "D", text: "What user signal we missed", traitEffects: { empathy: 2, curiosity: 1 } },
    ],
  },
  {
    id: "adaptive-28",
    text: "Which quality bar do you protect most?",
    category: "execution",
    difficultyLevel: 2,
    followUpTags: ["detail_orientation", "structured_thinking", "empathy"],
    isSeed: false,
    options: [
      { key: "A", text: "Accuracy", traitEffects: { detail_orientation: 3 } },
      { key: "B", text: "Usability", traitEffects: { empathy: 2, detail_orientation: 1 } },
      { key: "C", text: "Clarity", traitEffects: { communication_strength: 2, structured_thinking: 1 } },
      { key: "D", text: "Consistency", traitEffects: { structured_thinking: 2, detail_orientation: 1 } },
    ],
  },
  {
    id: "adaptive-29",
    text: "What is your first instinct with a new tool?",
    category: "technology",
    difficultyLevel: 2,
    followUpTags: ["technical_curiosity", "learning_agility", "risk_appetite"],
    isSeed: false,
    options: [
      { key: "A", text: "Explore settings and capabilities", traitEffects: { technical_curiosity: 2, curiosity: 1 } },
      { key: "B", text: "Use it on a real task immediately", traitEffects: { learning_agility: 2, execution_discipline: 1 } },
      { key: "C", text: "Read how experts use it", traitEffects: { curiosity: 2, structured_thinking: 1 } },
      { key: "D", text: "Push it until something breaks", traitEffects: { risk_appetite: 2, technical_curiosity: 1 } },
    ],
  },
  {
    id: "adaptive-30",
    text: "Which communication format do you prefer?",
    category: "communication",
    difficultyLevel: 2,
    followUpTags: ["communication_strength", "detail_orientation", "creative_expression"],
    isSeed: false,
    options: [
      { key: "A", text: "A concise written brief", traitEffects: { communication_strength: 2, structured_thinking: 1 } },
      { key: "B", text: "A visual explanation", traitEffects: { creative_expression: 2, communication_strength: 1 } },
      { key: "C", text: "A detailed checklist", traitEffects: { detail_orientation: 2, execution_discipline: 1 } },
      { key: "D", text: "A live conversation", traitEffects: { people_orientation: 2, communication_strength: 1 } },
    ],
  },
  {
    id: "adaptive-31",
    text: "What do you naturally track during a project?",
    category: "execution",
    difficultyLevel: 2,
    followUpTags: ["execution_discipline", "analytical_thinking", "people_orientation"],
    isSeed: false,
    options: [
      { key: "A", text: "Progress against milestones", traitEffects: { execution_discipline: 3 } },
      { key: "B", text: "Signals and metrics", traitEffects: { analytical_thinking: 3 } },
      { key: "C", text: "Team energy and blockers", traitEffects: { people_orientation: 2, empathy: 1 } },
      { key: "D", text: "Open questions and decisions", traitEffects: { structured_thinking: 2, communication_strength: 1 } },
    ],
  },
  {
    id: "adaptive-32",
    text: "Which statement sounds most like you?",
    category: "values",
    difficultyLevel: 2,
    followUpTags: ["autonomy_preference", "leadership_drive", "empathy", "curiosity"],
    isSeed: false,
    options: [
      { key: "A", text: "I like room to figure things out", traitEffects: { autonomy_preference: 3 } },
      { key: "B", text: "I like being responsible for outcomes", traitEffects: { leadership_drive: 2, execution_discipline: 1 } },
      { key: "C", text: "I like understanding people deeply", traitEffects: { empathy: 3 } },
      { key: "D", text: "I like following questions wherever they lead", traitEffects: { curiosity: 3 } },
    ],
  },
  {
    id: "adaptive-33",
    text: "How do you define a strong solution?",
    category: "problem_solving",
    difficultyLevel: 3,
    followUpTags: ["structured_thinking", "empathy", "technical_curiosity", "creative_expression"],
    isSeed: false,
    options: [
      { key: "A", text: "It solves the right problem simply", traitEffects: { structured_thinking: 2, empathy: 1 } },
      { key: "B", text: "It is technically sound", traitEffects: { technical_curiosity: 2, detail_orientation: 1 } },
      { key: "C", text: "It feels fresh and memorable", traitEffects: { creative_expression: 3 } },
      { key: "D", text: "It can be executed reliably", traitEffects: { execution_discipline: 2, structured_thinking: 1 } },
    ],
  },
  {
    id: "adaptive-34",
    text: "What do you do when people are stuck?",
    category: "leadership",
    difficultyLevel: 2,
    followUpTags: ["leadership_drive", "communication_strength", "empathy"],
    isSeed: false,
    options: [
      { key: "A", text: "Name the problem clearly", traitEffects: { communication_strength: 2, structured_thinking: 1 } },
      { key: "B", text: "Encourage the next small action", traitEffects: { leadership_drive: 2, execution_discipline: 1 } },
      { key: "C", text: "Check what support they need", traitEffects: { empathy: 3 } },
      { key: "D", text: "Create a better plan", traitEffects: { structured_thinking: 2, leadership_drive: 1 } },
    ],
  },
  {
    id: "adaptive-35",
    text: "Which future skill would you invest in first?",
    category: "learning",
    difficultyLevel: 2,
    followUpTags: ["learning_agility", "technical_curiosity", "communication_strength", "creative_expression"],
    isSeed: false,
    options: [
      { key: "A", text: "Coding and technical systems", traitEffects: { technical_curiosity: 3 } },
      { key: "B", text: "Storytelling and persuasion", traitEffects: { communication_strength: 3 } },
      { key: "C", text: "Design and visual expression", traitEffects: { creative_expression: 3 } },
      { key: "D", text: "Rapid learning methods", traitEffects: { learning_agility: 3 } },
    ],
  },
  {
    id: "adaptive-36",
    text: "You're asked to redesign a common household object. What's your first thought?",
    category: "creativity",
    difficultyLevel: 2,
    followUpTags: ["creative_expression", "analytical_thinking", "technical_curiosity"],
    isSeed: false,
    options: [
      { key: "A", text: "How to make it look more beautiful", traitEffects: { creative_expression: 3, empathy: 1 } },
      { key: "B", text: "How to make it function more efficiently", traitEffects: { analytical_thinking: 3, structured_thinking: 1 } },
      { key: "C", text: "What new technology could be integrated", traitEffects: { technical_curiosity: 3, curiosity: 1 } },
      { key: "D", text: "How to make it cheaper to produce", traitEffects: { execution_discipline: 2, analytical_thinking: 2 } },
    ],
  },
  {
    id: "adaptive-37",
    text: "You find a bug in a system you use daily. How do you react?",
    category: "problem_solving",
    difficultyLevel: 2,
    followUpTags: ["analytical_thinking", "technical_curiosity", "creative_expression"],
    isSeed: false,
    options: [
      { key: "A", text: "Try to find exactly what's causing it", traitEffects: { analytical_thinking: 3, technical_curiosity: 1 } },
      { key: "B", text: "Look for a creative workaround", traitEffects: { creative_expression: 2, execution_discipline: 2 } },
      { key: "C", text: "Report it with a detailed explanation", traitEffects: { communication_strength: 3, structured_thinking: 1 } },
      { key: "D", text: "Wait for someone else to fix it", traitEffects: { curiosity: 1 } },
    ],
  },
  {
    id: "adaptive-38",
    text: "A friend is frustrated with their career progress. How do you help?",
    category: "collaboration",
    difficultyLevel: 2,
    followUpTags: ["empathy", "structured_thinking", "creative_expression"],
    isSeed: false,
    options: [
      { key: "A", text: "Listen and validate their feelings", traitEffects: { empathy: 3, communication_strength: 1 } },
      { key: "B", text: "Help them map out a 5-year plan", traitEffects: { structured_thinking: 3, execution_discipline: 1 } },
      { key: "C", text: "Brainstorm unconventional career paths", traitEffects: { creative_expression: 3, curiosity: 1 } },
      { key: "D", text: "Research market data for their role", traitEffects: { analytical_thinking: 3, technical_curiosity: 1 } },
    ],
  },
  {
    id: "adaptive-39",
    text: "You need to explain a complex idea to a 5-year-old. What's your strategy?",
    category: "communication",
    difficultyLevel: 2,
    followUpTags: ["communication_strength", "creative_expression", "structured_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Use a simple, relatable story", traitEffects: { communication_strength: 3, creative_expression: 1 } },
      { key: "B", text: "Draw a diagram or use props", traitEffects: { structured_thinking: 2, creative_expression: 2 } },
      { key: "C", text: "Break it into three basic steps", traitEffects: { analytical_thinking: 1, structured_thinking: 3 } },
      { key: "D", text: "Focus on how it makes people feel", traitEffects: { empathy: 3, communication_strength: 1 } },
    ],
  },
  {
    id: "adaptive-40",
    text: "Your team is divided on which direction to take. What's your move?",
    category: "leadership",
    difficultyLevel: 2,
    followUpTags: ["leadership_drive", "communication_strength", "analytical_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Facilitate a compromise between both sides", traitEffects: { empathy: 1, communication_strength: 3 } },
      { key: "B", text: "List the pros and cons based on data", traitEffects: { analytical_thinking: 3, structured_thinking: 1 } },
      { key: "C", text: "Suggest a third, completely new option", traitEffects: { creative_expression: 3, curiosity: 1 } },
      { key: "D", text: "Step up and make a final decision", traitEffects: { leadership_drive: 3, execution_discipline: 1 } },
    ],
  },
  {
    id: "adaptive-41",
    text: "You have a massive project due in a month. How do you organize it?",
    category: "work_style",
    difficultyLevel: 2,
    followUpTags: ["structured_thinking", "execution_discipline", "analytical_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Create a detailed daily schedule", traitEffects: { structured_thinking: 3, execution_discipline: 1 } },
      { key: "B", text: "Identify the biggest risks first", traitEffects: { analytical_thinking: 3, curiosity: 1 } },
      { key: "C", text: "Focus on the creative vision first", traitEffects: { creative_expression: 3, communication_strength: 1 } },
      { key: "D", text: "Just start working and see where it goes", traitEffects: { execution_discipline: 1, curiosity: 3 } },
    ],
  },
  {
    id: "adaptive-42",
    text: "You encounter a word or concept you've never heard of. What do you do?",
    category: "learning",
    difficultyLevel: 2,
    followUpTags: ["curiosity", "analytical_thinking", "learning_agility"],
    isSeed: false,
    options: [
      { key: "A", text: "Immediately look it up and read deeply", traitEffects: { curiosity: 3, analytical_thinking: 1 } },
      { key: "B", text: "Ask someone to explain it to you", traitEffects: { communication_strength: 1, empathy: 2 } },
      { key: "C", text: "Try to deduce the meaning from context", traitEffects: { analytical_thinking: 3, structured_thinking: 1 } },
      { key: "D", text: "Note it down to research later", traitEffects: { execution_discipline: 1, learning_agility: 2 } },
    ],
  },
  {
    id: "adaptive-43",
    text: "A new technology is trending in your field. How do you approach it?",
    category: "learning",
    difficultyLevel: 2,
    followUpTags: ["technical_curiosity", "learning_agility", "analytical_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Experiment with it in a side project", traitEffects: { technical_curiosity: 3, creative_expression: 1 } },
      { key: "B", text: "Read technical documentation and reviews", traitEffects: { analytical_thinking: 3, technical_curiosity: 1 } },
      { key: "C", text: "Wait to see if it becomes a standard", traitEffects: { structured_thinking: 2 } },
      { key: "D", text: "Think about how it could help users", traitEffects: { empathy: 3, curiosity: 1 } },
    ],
  },
  {
    id: "adaptive-44",
    text: "You have an idea that could fail but might change everything. What do you do?",
    category: "creativity",
    difficultyLevel: 2,
    followUpTags: ["risk_appetite", "creative_expression", "execution_discipline"],
    isSeed: false,
    options: [
      { key: "A", text: "Pitch it to someone for feedback", traitEffects: { communication_strength: 3, creative_expression: 1 } },
      { key: "B", text: "Build a small prototype to test it", traitEffects: { execution_discipline: 3, technical_curiosity: 1 } },
      { key: "C", text: "Analyze all possible failure points", traitEffects: { analytical_thinking: 3, structured_thinking: 1 } },
      { key: "D", text: "Go all-in and trust your intuition", traitEffects: { risk_appetite: 3, creative_expression: 2 } },
    ],
  },
  {
    id: "adaptive-45",
    text: "You have a long list of small tasks. How do you tackle them?",
    category: "work_style",
    difficultyLevel: 2,
    followUpTags: ["execution_discipline", "structured_thinking", "technical_curiosity"],
    isSeed: false,
    options: [
      { key: "A", text: "Batch similar tasks together", traitEffects: { structured_thinking: 3, execution_discipline: 1 } },
      { key: "B", text: "Do the most difficult one first", traitEffects: { execution_discipline: 3, analytical_thinking: 1 } },
      { key: "C", text: "Automate as many as possible", traitEffects: { technical_curiosity: 3, creative_expression: 1 } },
      { key: "D", text: "Work on whatever feels easiest now", traitEffects: { empathy: 1 } },
    ],
  },
  {
    id: "adaptive-46",
    text: "A coworker is struggling to meet a deadline. What do you do?",
    category: "collaboration",
    difficultyLevel: 2,
    followUpTags: ["empathy", "execution_discipline", "communication_strength"],
    isSeed: false,
    options: [
      { key: "A", text: "Offer to take over some of their work", traitEffects: { execution_discipline: 3, empathy: 1 } },
      { key: "B", text: "Help them reorganize their priorities", traitEffects: { structured_thinking: 3, communication_strength: 1 } },
      { key: "C", text: "Listen to their frustrations", traitEffects: { empathy: 3, communication_strength: 1 } },
      { key: "D", text: "Focus on your own work to not fall behind", traitEffects: { execution_discipline: 2 } },
    ],
  },
  {
    id: "adaptive-47",
    text: "You want to learn a new language. How do you start?",
    category: "learning",
    difficultyLevel: 2,
    followUpTags: ["learning_agility", "curiosity", "communication_strength"],
    isSeed: false,
    options: [
      { key: "A", text: "Immerse yourself in movies and music", traitEffects: { creative_expression: 1, curiosity: 3 } },
      { key: "B", text: "Study grammar rules and structures", traitEffects: { structured_thinking: 3, analytical_thinking: 1 } },
      { key: "C", text: "Use a gamified app for quick wins", traitEffects: { execution_discipline: 2, technical_curiosity: 1 } },
      { key: "D", text: "Find a partner to practice speaking", traitEffects: { communication_strength: 3, empathy: 1 } },
    ],
  },
  {
    id: "adaptive-48",
    text: "You're reviewing a final report. What are you looking for?",
    category: "work_style",
    difficultyLevel: 2,
    followUpTags: ["detail_orientation", "analytical_thinking", "communication_strength"],
    isSeed: false,
    options: [
      { key: "A", text: "Errors in data and logic", traitEffects: { analytical_thinking: 3, detail_orientation: 2 } },
      { key: "B", text: "Spelling, grammar, and formatting", traitEffects: { detail_orientation: 3, execution_discipline: 1 } },
      { key: "C", text: "How well the story is told", traitEffects: { communication_strength: 3, creative_expression: 1 } },
      { key: "D", text: "If the conclusions are actionable", traitEffects: { execution_discipline: 3, analytical_thinking: 1 } },
    ],
  },
  {
    id: "adaptive-49",
    text: "You're given a vague assignment with no instructions. How do you feel?",
    category: "work_style",
    difficultyLevel: 2,
    followUpTags: ["autonomy_preference", "curiosity", "creative_expression"],
    isSeed: false,
    options: [
      { key: "A", text: "Excited by the freedom to explore", traitEffects: { curiosity: 3, creative_expression: 1 } },
      { key: "B", text: "Determined to create your own structure", traitEffects: { structured_thinking: 3, autonomy_preference: 2 } },
      { key: "C", text: "Anxious and need to ask for clarity", traitEffects: { communication_strength: 2, analytical_thinking: 1 } },
      { key: "D", text: "Ready to prototype several ideas", traitEffects: { execution_discipline: 3, creative_expression: 1 } },
    ],
  },
  {
    id: "adaptive-50",
    text: "You have a blank canvas and some paint. What's your process?",
    category: "creativity",
    difficultyLevel: 2,
    followUpTags: ["creative_expression", "curiosity", "structured_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Start with a clear, pre-planned sketch", traitEffects: { structured_thinking: 3, execution_discipline: 1 } },
      { key: "B", text: "Let your emotions guide the brush", traitEffects: { creative_expression: 3, empathy: 1 } },
      { key: "C", text: "Experiment with different textures", traitEffects: { curiosity: 3, technical_curiosity: 1 } },
      { key: "D", text: "Try to recreate a specific scene", traitEffects: { analytical_thinking: 1, detail_orientation: 3 } },
    ],
  },
  {
    id: "adaptive-51",
    text: "You're presented with a lot of data about a trend. What's your first step?",
    category: "problem_solving",
    difficultyLevel: 2,
    followUpTags: ["analytical_thinking", "curiosity", "structured_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Look for outliers and anomalies", traitEffects: { analytical_thinking: 3, curiosity: 1 } },
      { key: "B", text: "Visualize it in different charts", traitEffects: { creative_expression: 2, structured_thinking: 2 } },
      { key: "C", text: "Group it into logical categories", traitEffects: { structured_thinking: 3, analytical_thinking: 1 } },
      { key: "D", text: "Think about the human stories behind it", traitEffects: { empathy: 3, communication_strength: 1 } },
    ],
  },
  {
    id: "adaptive-52",
    text: "A customer is angry about a service delay. How do you respond?",
    category: "collaboration",
    difficultyLevel: 2,
    followUpTags: ["empathy", "communication_strength", "structured_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Apologize sincerely and empathize", traitEffects: { empathy: 3, communication_strength: 1 } },
      { key: "B", text: "Explain the technical reason for the delay", traitEffects: { technical_curiosity: 1, communication_strength: 2 } },
      { key: "C", text: "Offer a practical solution or discount", traitEffects: { execution_discipline: 3, analytical_thinking: 1 } },
      { key: "D", text: "Ask questions to understand their needs", traitEffects: { curiosity: 2, empathy: 2 } },
    ],
  },
  {
    id: "adaptive-53",
    text: "You're giving a presentation and notice the audience is bored. What do you do?",
    category: "communication",
    difficultyLevel: 2,
    followUpTags: ["communication_strength", "creative_expression", "empathy"],
    isSeed: false,
    options: [
      { key: "A", text: "Tell a quick, engaging story", traitEffects: { communication_strength: 3, creative_expression: 1 } },
      { key: "B", text: "Ask the audience a direct question", traitEffects: { communication_strength: 2, empathy: 2 } },
      { key: "C", text: "Speed up to get to the important parts", traitEffects: { execution_discipline: 3, analytical_thinking: 1 } },
      { key: "D", text: "Change your tone and body language", traitEffects: { creative_expression: 2, communication_strength: 2 } },
    ],
  },
  {
    id: "adaptive-54",
    text: "A new member joins your team and seems lost. How do you handle it?",
    category: "leadership",
    difficultyLevel: 2,
    followUpTags: ["leadership_drive", "empathy", "communication_strength"],
    isSeed: false,
    options: [
      { key: "A", text: "Give them a tour and introduce everyone", traitEffects: { people_orientation: 3, communication_strength: 1 } },
      { key: "B", text: "Assign them a small, clear task", traitEffects: { execution_discipline: 3, structured_thinking: 1 } },
      { key: "C", text: "Explain the team's goals and vision", traitEffects: { communication_strength: 3, leadership_drive: 1 } },
      { key: "D", text: "Ask them about their background and skills", traitEffects: { curiosity: 2, empathy: 2 } },
    ],
  },
  {
    id: "adaptive-55",
    text: "Your workspace is cluttered and disorganized. How does it affect you?",
    category: "work_style",
    difficultyLevel: 2,
    followUpTags: ["structured_thinking", "creative_expression", "execution_discipline"],
    isSeed: false,
    options: [
      { key: "A", text: "It's fine, I know where everything is", traitEffects: { creative_expression: 1, curiosity: 2 } },
      { key: "B", text: "I can't focus until I clean it up", traitEffects: { structured_thinking: 3, execution_discipline: 1 } },
      { key: "C", text: "It's a sign of a busy, productive mind", traitEffects: { execution_discipline: 1, creative_expression: 2 } },
      { key: "D", text: "I use the chaos to find new connections", traitEffects: { creative_expression: 3, curiosity: 2 } },
    ],
  },
  {
    id: "adaptive-56",
    text: "You're visiting a new city for the first time. How do you spend your day?",
    category: "learning",
    difficultyLevel: 2,
    followUpTags: ["curiosity", "structured_thinking", "empathy"],
    isSeed: false,
    options: [
      { key: "A", text: "Follow a strictly planned itinerary", traitEffects: { structured_thinking: 3, execution_discipline: 1 } },
      { key: "B", text: "Wander around and get lost", traitEffects: { curiosity: 3, creative_expression: 2 } },
      { key: "C", text: "Visit all the major historical sites", traitEffects: { analytical_thinking: 2, curiosity: 2 } },
      { key: "D", text: "Find where the locals eat and hang out", traitEffects: { empathy: 3, people_orientation: 2 } },
    ],
  },
  {
    id: "adaptive-57",
    text: "You're curious about how a specific software works. What do you do?",
    category: "learning",
    difficultyLevel: 2,
    followUpTags: ["technical_curiosity", "analytical_thinking", "curiosity"],
    isSeed: false,
    options: [
      { key: "A", text: "Search for the source code online", traitEffects: { technical_curiosity: 3, curiosity: 1 } },
      { key: "B", text: "Read blog posts about its architecture", traitEffects: { analytical_thinking: 3, technical_curiosity: 1 } },
      { key: "C", text: "Try to reverse-engineer its behavior", traitEffects: { analytical_thinking: 3, creative_expression: 1 } },
      { key: "D", text: "Ask an expert to explain it to you", traitEffects: { communication_strength: 2, empathy: 2 } },
    ],
  },
  {
    id: "adaptive-58",
    text: "You're offered a high-risk, high-reward opportunity. What's your reaction?",
    category: "work_style",
    difficultyLevel: 2,
    followUpTags: ["risk_appetite", "analytical_thinking", "leadership_drive"],
    isSeed: false,
    options: [
      { key: "A", text: "Analyze the mathematical odds of success", traitEffects: { analytical_thinking: 3, structured_thinking: 1 } },
      { key: "B", text: "Get excited about the potential impact", traitEffects: { creative_expression: 1, communication_strength: 2 } },
      { key: "C", text: "Think about the worst-case scenario", traitEffects: { analytical_thinking: 2, detail_orientation: 2 } },
      { key: "D", text: "Trust your gut and take the leap", traitEffects: { risk_appetite: 3, leadership_drive: 1 } },
    ],
  },
  {
    id: "adaptive-59",
    text: "You've hit a roadblock in your project. What's your next step?",
    category: "problem_solving",
    difficultyLevel: 2,
    followUpTags: ["analytical_thinking", "curiosity", "learning_agility"],
    isSeed: false,
    options: [
      { key: "A", text: "Take a break to clear your head", traitEffects: { creative_expression: 2, curiosity: 1 } },
      { key: "B", text: "Systematically test every variable", traitEffects: { analytical_thinking: 3, technical_curiosity: 1 } },
      { key: "C", text: "Ask a colleague for a fresh perspective", traitEffects: { communication_strength: 2, empathy: 2 } },
      { key: "D", text: "Research how others solved this problem", traitEffects: { curiosity: 3, learning_agility: 2 } },
    ],
  },
  {
    id: "adaptive-60",
    text: "You're in a group project and someone isn't contributing. How do you handle it?",
    category: "collaboration",
    difficultyLevel: 2,
    followUpTags: ["empathy", "structured_thinking", "leadership_drive"],
    isSeed: false,
    options: [
      { key: "A", text: "Talk to them privately to find out why", traitEffects: { empathy: 3, communication_strength: 2 } },
      { key: "B", text: "Clearly redefine their tasks and deadlines", traitEffects: { structured_thinking: 3, execution_discipline: 2 } },
      { key: "C", text: "Do their work yourself to ensure quality", traitEffects: { execution_discipline: 3, detail_orientation: 2 } },
      { key: "D", text: "Bring it up in a group meeting", traitEffects: { communication_strength: 3, leadership_drive: 1 } },
    ],
  },
  {
    id: "adaptive-61",
    text: "You're attending a workshop. Which part do you find most valuable?",
    category: "learning",
    difficultyLevel: 2,
    followUpTags: ["learning_agility", "curiosity", "communication_strength"],
    isSeed: false,
    options: [
      { key: "A", text: "The hands-on practice sessions", traitEffects: { execution_discipline: 3, technical_curiosity: 2 } },
      { key: "B", text: "The theoretical explanations", traitEffects: { analytical_thinking: 3, structured_thinking: 2 } },
      { key: "C", text: "Networking with other participants", traitEffects: { communication_strength: 3, people_orientation: 2 } },
      { key: "D", text: "The Q&A with the instructor", traitEffects: { curiosity: 3, communication_strength: 2 } },
    ],
  },
  {
    id: "adaptive-62",
    text: "You're writing a story. What's the most important element to you?",
    category: "creativity",
    difficultyLevel: 2,
    followUpTags: ["creative_expression", "empathy", "communication_strength"],
    isSeed: false,
    options: [
      { key: "A", text: "A complex and logical plot", traitEffects: { analytical_thinking: 2, structured_thinking: 3 } },
      { key: "B", text: "Deeply emotional character arcs", traitEffects: { empathy: 3, creative_expression: 2 } },
      { key: "C", text: "A unique and imaginative world", traitEffects: { creative_expression: 3, curiosity: 2 } },
      { key: "D", text: "Clear and impactful themes", traitEffects: { communication_strength: 3, analytical_thinking: 1 } },
    ],
  },
  {
    id: "adaptive-63",
    text: "You're trying to figure out why a machine isn't working. What's your method?",
    category: "problem_solving",
    difficultyLevel: 2,
    followUpTags: ["analytical_thinking", "technical_curiosity", "curiosity"],
    isSeed: false,
    options: [
      { key: "A", text: "Read the manual from cover to cover", traitEffects: { analytical_thinking: 2, detail_orientation: 3 } },
      { key: "B", text: "Take it apart to see how it works", traitEffects: { curiosity: 3, technical_curiosity: 2 } },
      { key: "C", text: "Search for common issues online", traitEffects: { analytical_thinking: 3, technical_curiosity: 1 } },
      { key: "D", text: "Try turning it off and on again", traitEffects: { execution_discipline: 2 } },
    ],
  },
  {
    id: "adaptive-64",
    text: "You're a mediator in a conflict between two friends. What's your goal?",
    category: "collaboration",
    difficultyLevel: 2,
    followUpTags: ["empathy", "communication_strength", "analytical_thinking"],
    isSeed: false,
    options: [
      { key: "A", text: "Find a fair and logical solution", traitEffects: { analytical_thinking: 3, structured_thinking: 1 } },
      { key: "B", text: "Make sure both feel heard and understood", traitEffects: { empathy: 3, communication_strength: 2 } },
      { key: "C", text: "Keep the peace at any cost", traitEffects: { empathy: 2, people_orientation: 2 } },
      { key: "D", text: "Clarify the misunderstandings", traitEffects: { communication_strength: 3, analytical_thinking: 2 } },
    ],
  },
  {
    id: "adaptive-65",
    text: "You're writing an email to a senior executive. What's your main focus?",
    category: "communication",
    difficultyLevel: 2,
    followUpTags: ["communication_strength", "structured_thinking", "detail_orientation"],
    isSeed: false,
    options: [
      { key: "A", text: "Being as concise and clear as possible", traitEffects: { communication_strength: 3, structured_thinking: 2 } },
      { key: "B", text: "Showing your deep knowledge of the topic", traitEffects: { analytical_thinking: 2, detail_orientation: 2 } },
      { key: "C", text: "Making a persuasive argument", traitEffects: { communication_strength: 3, creative_expression: 1 } },
      { key: "D", text: "Formatting it perfectly", traitEffects: { detail_orientation: 3, execution_discipline: 1 } },
    ],
  },
];

export const questionBank: AssessmentQuestion[] = [...seedQuestions, ...adaptiveQuestions];
