import { CareerProfile } from "./types";

export const careerOntology: CareerProfile[] = [
  // --- SOFTWARE ---
  {
    id: "frontend-dev",
    title: "Frontend Developer",
    cluster: "Software",
    requiredTraits: { technicalAptitude: 8, creativity: 7, structuredThinking: 6 },
    preferredWorkStyle: "Visual and logical iterative building",
    fulfillingSkills: ["JavaScript", "React", "CSS/UI Design", "Problem Solving"],
    commonTasks: ["Building user interfaces", "Optimizing performance", "Collaborating with designers"],
    growthPotential: "High",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Rapidly changing frameworks", "Cross-browser compatibility issues"],
  },
  {
    id: "backend-dev",
    title: "Backend Developer",
    cluster: "Software",
    requiredTraits: { technicalAptitude: 9, analysis: 8, structuredThinking: 9 },
    preferredWorkStyle: "Building robust systems and logic",
    fulfillingSkills: ["Node.js", "Databases", "API Design", "System Architecture"],
    commonTasks: ["Designing database schemas", "Building server-side logic", "Ensuring security"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Scaling complexities", "Data integrity issues"],
  },
  {
    id: "devops-engineer",
    title: "DevOps Engineer",
    cluster: "Software",
    requiredTraits: { technicalAptitude: 9, execution: 8, structuredThinking: 9 },
    preferredWorkStyle: "Automating and optimizing deployment pipelines",
    fulfillingSkills: ["Cloud Infrastructure", "CI/CD", "Docker/Kubernetes", "Scripting"],
    commonTasks: ["Managing cloud resources", "Automating deployments", "Monitoring system health"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["System outages", "Complex configuration management"],
  },
  {
    id: "cybersecurity-analyst",
    title: "Cybersecurity Analyst",
    cluster: "Software",
    requiredTraits: { technicalAptitude: 8, analysis: 9, curiosity: 8 },
    preferredWorkStyle: "Protecting systems and investigating threats",
    fulfillingSkills: ["Network Security", "Threat Hunting", "Incident Response", "Compliance"],
    commonTasks: ["Monitoring for breaches", "Vulnerability assessments", "Security auditing"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Constant evolution of threats", "High-pressure incident response"],
  },

  // --- DESIGN ---
  {
    id: "ux-designer",
    title: "UX Designer",
    cluster: "Design",
    requiredTraits: { empathy: 9, creativity: 8, analysis: 7 },
    preferredWorkStyle: "Advocating for users through research and design",
    fulfillingSkills: ["User Research", "Wireframing", "Prototyping", "Information Architecture"],
    commonTasks: ["Conducting user interviews", "Creating user flows", "Testing prototypes"],
    growthPotential: "High",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Balancing user needs with business goals", "Communicating design value"],
  },
  {
    id: "ui-designer",
    title: "UI Designer",
    cluster: "Design",
    requiredTraits: { creativity: 9, technicalAptitude: 6, execution: 7 },
    preferredWorkStyle: "Creating beautiful and functional interfaces",
    fulfillingSkills: ["Visual Design", "Typography", "Color Theory", "Design Systems"],
    commonTasks: ["Designing layout screens", "Creating style guides", "Handoff to developers"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Maintaining consistency", "Keeping up with design trends"],
  },
  {
    id: "graphic-designer",
    title: "Graphic Designer",
    cluster: "Design",
    requiredTraits: { creativity: 10, communication: 7, execution: 8 },
    preferredWorkStyle: "Visual storytelling and branding",
    fulfillingSkills: ["Adobe Creative Suite", "Branding", "Layout Design", "Illustration"],
    commonTasks: ["Logo design", "Marketing materials", "Brand identity development"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Subjective client feedback", "Strict deadlines"],
  },

  // --- DATA ---
  {
    id: "data-scientist",
    title: "Data Scientist",
    cluster: "Data",
    requiredTraits: { analysis: 9, technicalAptitude: 8, curiosity: 9 },
    preferredWorkStyle: "Uncovering insights from complex datasets",
    fulfillingSkills: ["Python/R", "Machine Learning", "Statistics", "Data Storytelling"],
    commonTasks: ["Building predictive models", "Exploratory data analysis", "Communicating insights"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Data quality issues", "Explaining complex models to stakeholders"],
  },
  {
    id: "data-analyst",
    title: "Data Analyst",
    cluster: "Data",
    requiredTraits: { analysis: 8, structuredThinking: 8, communication: 7 },
    preferredWorkStyle: "Reporting and visualizing data for decision making",
    fulfillingSkills: ["SQL", "Excel", "Tableau/PowerBI", "Data Cleaning"],
    commonTasks: ["Creating dashboards", "Running queries", "Reporting on KPIs"],
    growthPotential: "High",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Repetitive data cleaning", "Misinterpretation of results"],
  },
  {
    id: "machine-learning-engineer",
    title: "ML Engineer",
    cluster: "Data",
    requiredTraits: { technicalAptitude: 10, analysis: 9, structuredThinking: 8 },
    preferredWorkStyle: "Deploying and scaling AI models",
    fulfillingSkills: ["PyTorch/TensorFlow", "Software Engineering", "Algorithms", "Model Monitoring"],
    commonTasks: ["Training ML models", "Optimizing model performance", "Productionizing AI"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Model drift", "Compute resource management"],
  },

  // --- PRODUCT ---
  {
    id: "product-manager",
    title: "Product Manager",
    cluster: "Product",
    requiredTraits: { communication: 9, structuredThinking: 8, empathy: 7, execution: 8 },
    preferredWorkStyle: "Leading cross-functional teams to build the right thing",
    fulfillingSkills: ["Product Strategy", "Roadmapping", "Stakeholder Management", "Prioritization"],
    commonTasks: ["Defining product vision", "Writing requirements", "Managing backlogs"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Saying 'no' to stakeholders", "Ambiguous requirements"],
  },
  {
    id: "product-owner",
    title: "Product Owner",
    cluster: "Product",
    requiredTraits: { execution: 9, structuredThinking: 8, communication: 7 },
    preferredWorkStyle: "Managing the day-to-day agile development process",
    fulfillingSkills: ["Agile/Scrum", "Backlog Grooming", "User Stories", "QA Coordination"],
    commonTasks: ["Prioritizing tasks", "Answering dev questions", "Acceptance testing"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Scope creep", "Team bandwidth issues"],
  },

  // --- MARKETING ---
  {
    id: "digital-marketer",
    title: "Digital Marketer",
    cluster: "Marketing",
    requiredTraits: { creativity: 7, analysis: 7, execution: 8 },
    preferredWorkStyle: "Running campaigns to grow online presence",
    fulfillingSkills: ["SEO/SEM", "Content Marketing", "Paid Ads", "Analytics"],
    commonTasks: ["Managing social media", "Optimizing ad spend", "Email campaigns"],
    growthPotential: "High",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Changing algorithms", "High competition"],
  },
  {
    id: "brand-manager",
    title: "Brand Manager",
    cluster: "Marketing",
    requiredTraits: { creativity: 9, communication: 8, curiosity: 7 },
    preferredWorkStyle: "Defining and protecting the brand identity",
    fulfillingSkills: ["Brand Strategy", "Market Research", "Campaign Management", "Public Relations"],
    commonTasks: ["Brand positioning", "Marketing strategy", "PR coordination"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Brand reputation management", "Measuring brand ROI"],
  },
  {
    id: "content-strategist",
    title: "Content Strategist",
    cluster: "Marketing",
    requiredTraits: { creativity: 8, structuredThinking: 7, communication: 9 },
    preferredWorkStyle: "Planning and managing content ecosystems",
    fulfillingSkills: ["Copywriting", "SEO", "Editorial Planning", "Governance"],
    commonTasks: ["Auditing content", "Defining voice and tone", "Managing calendars"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Content overload", "Aligning many stakeholders"],
  },

  // --- SALES ---
  {
    id: "account-executive",
    title: "Account Executive",
    cluster: "Sales",
    requiredTraits: { communication: 10, empathy: 7, execution: 9 },
    preferredWorkStyle: "Closing deals and building relationships",
    fulfillingSkills: ["Negotiation", "Prospecting", "CRM Management", "Sales Presentation"],
    commonTasks: ["Cold outreach", "Demoing products", "Negotiating contracts"],
    growthPotential: "High",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Rejection", "Aggressive quotas"],
  },
  {
    id: "sales-development-rep",
    title: "SDR / BDR",
    cluster: "Sales",
    requiredTraits: { communication: 8, execution: 10, curiosity: 6 },
    preferredWorkStyle: "Finding and qualifying new leads",
    fulfillingSkills: ["Outbound Outreach", "Lead Qualification", "Email Sequences", "Social Selling"],
    commonTasks: ["Cold calling", "Emailing prospects", "Booking meetings"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Low",
    possibleChallenges: ["Burnout", "High volume of rejection"],
  },

  // --- FINANCE ---
  {
    id: "financial-analyst",
    title: "Financial Analyst",
    cluster: "Finance",
    requiredTraits: { analysis: 9, structuredThinking: 9, technicalAptitude: 7 },
    preferredWorkStyle: "Modeling and forecasting financial health",
    fulfillingSkills: ["Financial Modeling", "Excel Mastery", "Forecasting", "Valuation"],
    commonTasks: ["Building budget models", "Analyzing trends", "Reporting to leadership"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Extreme attention to detail", "Tight reporting cycles"],
  },
  {
    id: "investment-banker",
    title: "Investment Banker",
    cluster: "Finance",
    requiredTraits: { execution: 10, analysis: 8, communication: 8 },
    preferredWorkStyle: "Executing high-stakes financial transactions",
    fulfillingSkills: ["M&A Advisory", "Financial Diligence", "Pitching", "Transaction Management"],
    commonTasks: ["Capital raising", "Advising on mergers", "Due diligence"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Long hours", "Extreme pressure"],
  },

  // --- OPERATIONS ---
  {
    id: "operations-manager",
    title: "Operations Manager",
    cluster: "Operations",
    requiredTraits: { execution: 9, structuredThinking: 9, analysis: 7 },
    preferredWorkStyle: "Optimizing internal processes and logistics",
    fulfillingSkills: ["Process Improvement", "Project Management", "Logistics", "Budgeting"],
    commonTasks: ["Managing workflows", "Vendor management", "Resource allocation"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Crisis management", "Inefficient legacy systems"],
  },
  {
    id: "supply-chain-specialist",
    title: "Supply Chain Specialist",
    cluster: "Operations",
    requiredTraits: { structuredThinking: 10, analysis: 8, execution: 7 },
    preferredWorkStyle: "Managing the flow of goods and services",
    fulfillingSkills: ["Inventory Management", "Procurement", "Logistics Planning", "Risk Mitigation"],
    commonTasks: ["Sourcing suppliers", "Tracking shipments", "Optimizing stock levels"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Global disruptions", "Logistical bottlenecks"],
  },

  // --- HR ---
  {
    id: "hr-generalist",
    title: "HR Generalist",
    cluster: "HR",
    requiredTraits: { empathy: 8, communication: 8, structuredThinking: 7 },
    preferredWorkStyle: "Supporting employees and managing policies",
    fulfillingSkills: ["Employee Relations", "Compliance", "Recruiting", "Onboarding"],
    commonTasks: ["Resolving conflicts", "Updating policies", "Onboarding new hires"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Difficult employee conversations", "Policy compliance"],
  },
  {
    id: "talent-acquisition",
    title: "Recruiter",
    cluster: "HR",
    requiredTraits: { communication: 9, empathy: 7, curiosity: 8 },
    preferredWorkStyle: "Finding and hiring top talent",
    fulfillingSkills: ["Sourcing", "Interviewing", "Negotiation", "Employer Branding"],
    commonTasks: ["Reviewing resumes", "Conducting interviews", "Managing candidate pipeline"],
    growthPotential: "Medium",
    difficultyLevel: "Low",
    learningCurve: "Low",
    possibleChallenges: ["High volume roles", "Candidate ghosting"],
  },

  // --- ENTREPRENEURSHIP ---
  {
    id: "startup-founder",
    title: "Startup Founder",
    cluster: "Entrepreneurship",
    requiredTraits: { creativity: 9, execution: 10, curiosity: 9, communication: 8 },
    preferredWorkStyle: "Building a company from the ground up",
    fulfillingSkills: ["Fundraising", "Product Vision", "Hiring", "Sales/Marketing"],
    commonTasks: ["Pitching to investors", "Recruiting teams", "Finding product-market fit"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["High risk of failure", "Constant uncertainty"],
  },
  {
    id: "product-strategist",
    title: "Product Strategist",
    cluster: "Entrepreneurship",
    requiredTraits: { analysis: 9, creativity: 8, structuredThinking: 8 },
    preferredWorkStyle: "Consulting on how to build and scale new ventures",
    fulfillingSkills: ["Market Analysis", "Business Modeling", "Go-to-market Strategy", "Growth Loops"],
    commonTasks: ["Competitive research", "Pricing strategy", "Growth experiments"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Vague client goals", "Fast-moving markets"],
  },

  // --- RESEARCH ---
  {
    id: "ux-researcher",
    title: "UX Researcher",
    cluster: "Research",
    requiredTraits: { curiosity: 10, empathy: 8, analysis: 9 },
    preferredWorkStyle: "Systematically studying users to guide design",
    fulfillingSkills: ["Qualitative Methods", "Quantitative Research", "Synthesizing Insights", "Observation"],
    commonTasks: ["User testing", "Survey design", "Personas creation"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Finding the right participants", "Getting buy-in for research"],
  },
  {
    id: "market-research-analyst",
    title: "Market Researcher",
    cluster: "Research",
    requiredTraits: { analysis: 10, curiosity: 8, structuredThinking: 7 },
    preferredWorkStyle: "Analyzing market trends and competitor behavior",
    fulfillingSkills: ["Data Mining", "Consumer Psychology", "Statistical Analysis", "Reporting"],
    commonTasks: ["Tracking market trends", "Consumer surveys", "Competitor auditing"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Data overload", "Short-lived trends"],
  },

  // --- EDUCATION ---
  {
    id: "learning-designer",
    title: "Instructional Designer",
    cluster: "Education",
    requiredTraits: { structuredThinking: 9, creativity: 7, empathy: 8 },
    preferredWorkStyle: "Creating effective learning experiences and curricula",
    fulfillingSkills: ["Curriculum Design", "LMS Management", "Educational Psychology", "Storyboarding"],
    commonTasks: ["Designing course modules", "Collaborating with SMEs", "Evaluating learning outcomes"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Outdated legacy materials", "Balancing complexity and simplicity"],
  },
  {
    id: "corporate-trainer",
    title: "Corporate Trainer",
    cluster: "Education",
    requiredTraits: { communication: 10, empathy: 8, execution: 7 },
    preferredWorkStyle: "Teaching and facilitating workshops for adults",
    fulfillingSkills: ["Public Speaking", "Workshop Facilitation", "Content Creation", "Needs Assessment"],
    commonTasks: ["Leading training sessions", "Creating training manuals", "Coaching employees"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Disengaged audiences", "Measuring training impact"],
  },

  // --- CONTENT ---
  {
    id: "copywriter",
    title: "Copywriter",
    cluster: "Content",
    requiredTraits: { creativity: 9, empathy: 8, execution: 7 },
    preferredWorkStyle: "Writing persuasive and engaging copy",
    fulfillingSkills: ["Writing", "Editing", "Sales Psychology", "SEO Basics"],
    commonTasks: ["Writing ad copy", "Website content", "Social media posts"],
    growthPotential: "Medium",
    difficultyLevel: "Low",
    learningCurve: "Medium",
    possibleChallenges: ["Writer's block", "High volume work"],
  },
  {
    id: "video-producer",
    title: "Video Producer",
    cluster: "Content",
    requiredTraits: { creativity: 8, execution: 9, technicalAptitude: 7 },
    preferredWorkStyle: "Coordinating all aspects of video production",
    fulfillingSkills: ["Video Editing", "Scripting", "Project Management", "Direction"],
    commonTasks: ["Managing film shoots", "Editing video", "Storyboarding"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "High",
    possibleChallenges: ["Technical gear failures", "Scope and budget management"],
  },

  // --- PSYCHOLOGY ---
  {
    id: "career-coach",
    title: "Career Coach",
    cluster: "Psychology",
    requiredTraits: { empathy: 10, communication: 9, analysis: 7 },
    preferredWorkStyle: "Guiding individuals through career transitions",
    fulfillingSkills: ["Active Listening", "Goal Setting", "Interview Prep", "Resume Building"],
    commonTasks: ["1-on-1 coaching", "Reviewing resumes", "Running workshops"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Emotional labor", "Managing client expectations"],
  },
  {
    id: "user-experience-researcher-psych",
    title: "UX Researcher (Psych Focus)",
    cluster: "Psychology",
    requiredTraits: { curiosity: 9, analysis: 9, empathy: 8 },
    preferredWorkStyle: "Applying psychological principles to user behavior",
    fulfillingSkills: ["Cognitive Psychology", "Research Ethics", "Statistical Analysis", "Behavioral Design"],
    commonTasks: ["Heuristic evaluations", "Cognitive walkthroughs", "Research planning"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Bridging academia and industry", "Fast deadlines"],
  },

  // --- BUSINESS STRATEGY ---
  {
    id: "management-consultant",
    title: "Management Consultant",
    cluster: "Business Strategy",
    requiredTraits: { analysis: 9, structuredThinking: 9, communication: 9, execution: 8 },
    preferredWorkStyle: "Solving high-level business problems for clients",
    fulfillingSkills: ["Problem Solving", "Strategic Frameworks", "Presentation Skills", "Financial Analysis"],
    commonTasks: ["Client interviews", "Creating slide decks", "Market analysis"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Frequent travel", "Heavy workload"],
  },
  {
    id: "business-analyst",
    title: "Business Analyst",
    cluster: "Business Strategy",
    requiredTraits: { structuredThinking: 9, analysis: 8, communication: 8 },
    preferredWorkStyle: "Translating business needs into technical requirements",
    fulfillingSkills: ["Requirements Gathering", "Process Mapping", "SQL", "Stakeholder Communication"],
    commonTasks: ["Documenting workflows", "Running workshops", "Bridge between biz and tech"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Conflicting requirements", "Gap between biz and dev"],
  },

  // --- ADDITIONAL SOFTWARE ---
  {
    id: "fullstack-dev",
    title: "Fullstack Developer",
    cluster: "Software",
    requiredTraits: { technicalAptitude: 9, execution: 8, curiosity: 7 },
    preferredWorkStyle: "Working across the entire application stack",
    fulfillingSkills: ["JS/TS", "Frontend + Backend", "Database Management", "Deployment"],
    commonTasks: ["Building end-to-end features", "API integration", "System debugging"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Broad context switching", "Keeping up with full stack tech"],
  },
  {
    id: "mobile-dev",
    title: "Mobile Developer",
    cluster: "Software",
    requiredTraits: { technicalAptitude: 8, creativity: 6, execution: 8 },
    preferredWorkStyle: "Building mobile-first experiences",
    fulfillingSkills: ["Swift/Kotlin", "React Native/Flutter", "App Store Guidelines", "Mobile UI"],
    commonTasks: ["iOS/Android development", "Mobile performance tuning", "Bug fixing"],
    growthPotential: "High",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Platform fragmentation", "Strict app review processes"],
  },

  // --- ADDITIONAL DESIGN ---
  {
    id: "product-designer",
    title: "Product Designer",
    cluster: "Design",
    requiredTraits: { creativity: 8, analysis: 7, structuredThinking: 7, communication: 7 },
    preferredWorkStyle: "End-to-end design from research to high-fidelity",
    fulfillingSkills: ["Figma", "Design Thinking", "Interaction Design", "Prototyping"],
    commonTasks: ["User research", "High-fi mocks", "Design systems work"],
    growthPotential: "High",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Design at scale", "Cross-team coordination"],
  },
  {
    id: "motion-designer",
    title: "Motion Designer",
    cluster: "Design",
    requiredTraits: { creativity: 10, execution: 9, technicalAptitude: 7 },
    preferredWorkStyle: "Bringing interfaces and graphics to life",
    fulfillingSkills: ["After Effects", "Lottie", "Animation Principles", "Visual Storytelling"],
    commonTasks: ["UI animations", "Promotional videos", "Micro-interactions"],
    growthPotential: "Medium",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Long rendering times", "Complex keyframing"],
  },

  // --- ADDITIONAL DATA ---
  {
    id: "data-engineer",
    title: "Data Engineer",
    cluster: "Data",
    requiredTraits: { technicalAptitude: 9, structuredThinking: 9, execution: 8 },
    preferredWorkStyle: "Building and maintaining data pipelines",
    fulfillingSkills: ["ETL", "Python/Java", "Big Data (Spark/Hadoop)", "Data Warehousing"],
    commonTasks: ["Building data pipelines", "Database optimization", "Data modeling"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Data infrastructure stability", "Scaling issues"],
  },
  {
    id: "business-intelligence-dev",
    title: "BI Developer",
    cluster: "Data",
    requiredTraits: { analysis: 8, structuredThinking: 8, execution: 7 },
    preferredWorkStyle: "Designing and developing reporting solutions",
    fulfillingSkills: ["SQL", "ETL", "BI Tools", "Data Visualization"],
    commonTasks: ["Building reports", "Managing data warehouses", "Training users"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Messy source data", "Changing reporting requirements"],
  },

  // --- ADDITIONAL MARKETING ---
  {
    id: "growth-hacker",
    title: "Growth Marketer",
    cluster: "Marketing",
    requiredTraits: { analysis: 9, curiosity: 10, execution: 8 },
    preferredWorkStyle: "Rapid experimentation to drive growth",
    fulfillingSkills: ["A/B Testing", "Funnel Optimization", "Data Analytics", "Performance Marketing"],
    commonTasks: ["Running growth experiments", "Optimizing conversion rates", "Virality planning"],
    growthPotential: "High",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["High failure rate of experiments", "Saturation of channels"],
  },
  {
    id: "seo-specialist",
    title: "SEO Specialist",
    cluster: "Marketing",
    requiredTraits: { analysis: 8, curiosity: 8, execution: 7 },
    preferredWorkStyle: "Improving search engine rankings",
    fulfillingSkills: ["Keyword Research", "Technical SEO", "On-page Optimization", "Link Building"],
    commonTasks: ["SEO audits", "Content recommendations", "Backlink tracking"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Search algorithm changes", "Slow results"],
  },

  // --- ADDITIONAL SALES ---
  {
    id: "customer-success-manager",
    title: "Customer Success Manager",
    cluster: "Sales",
    requiredTraits: { empathy: 9, communication: 9, structuredThinking: 7 },
    preferredWorkStyle: "Ensuring clients achieve their goals with the product",
    fulfillingSkills: ["Client Relationship Management", "Onboarding", "Retention", "Upselling"],
    commonTasks: ["Client check-ins", "Training sessions", "Managing renewals"],
    growthPotential: "High",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Churn prevention", "Managing difficult accounts"],
  },
  {
    id: "solutions-architect-sales",
    title: "Solutions Architect (Sales)",
    cluster: "Sales",
    requiredTraits: { technicalAptitude: 9, communication: 9, analysis: 7 },
    preferredWorkStyle: "Designing technical solutions to win deals",
    fulfillingSkills: ["System Design", "Cloud Architecture", "Public Speaking", "Prototyping"],
    commonTasks: ["Technical demos", "Scoping implementations", "Answering RFPs"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Complex integrations", "Translating tech to biz"],
  },

  // --- ADDITIONAL FINANCE ---
  {
    id: "tax-accountant",
    title: "Tax Accountant",
    cluster: "Finance",
    requiredTraits: { structuredThinking: 10, analysis: 8, execution: 8 },
    preferredWorkStyle: "Navigating tax regulations and compliance",
    fulfillingSkills: ["Tax Laws", "Accounting Software", "Compliance", "Advisory"],
    commonTasks: ["Filing returns", "Tax planning", "Auditing"],
    growthPotential: "Medium",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Changing tax laws", "High workload during tax season"],
  },
  {
    id: "risk-manager-finance",
    title: "Financial Risk Manager",
    cluster: "Finance",
    requiredTraits: { analysis: 10, structuredThinking: 9, technicalAptitude: 7 },
    preferredWorkStyle: "Identifying and mitigating financial risks",
    fulfillingSkills: ["Risk Modeling", "Statistics", "Derivatives", "Regulations"],
    commonTasks: ["Scenario analysis", "Stress testing", "Reporting to board"],
    growthPotential: "High",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Black swan events", "Regulatory complexity"],
  },

  // --- ADDITIONAL OPERATIONS ---
  {
    id: "project-manager-ops",
    title: "Project Manager",
    cluster: "Operations",
    requiredTraits: { structuredThinking: 10, execution: 9, communication: 8 },
    preferredWorkStyle: "Coordinating resources and timelines to meet goals",
    fulfillingSkills: ["PMP/Agile", "Resource Allocation", "Risk Management", "Budgeting"],
    commonTasks: ["Managing timelines", "Stakeholder meetings", "Resource planning"],
    growthPotential: "Medium",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Scope creep", "Team conflicts"],
  },
  {
    id: "facilities-manager",
    title: "Facilities Manager",
    cluster: "Operations",
    requiredTraits: { execution: 9, communication: 7, structuredThinking: 8 },
    preferredWorkStyle: "Managing the physical environment of an organization",
    fulfillingSkills: ["Space Planning", "Vendor Management", "Maintenance", "Security"],
    commonTasks: ["Building maintenance", "Safety inspections", "Vendor coordination"],
    growthPotential: "Low",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Physical emergencies", "Budget constraints"],
  },

  // --- ADDITIONAL EDUCATION ---
  {
    id: "academic-researcher",
    title: "Academic Researcher",
    cluster: "Research",
    requiredTraits: { curiosity: 10, analysis: 10, structuredThinking: 8 },
    preferredWorkStyle: "Expanding knowledge through rigorous study and publication",
    fulfillingSkills: ["Experimental Design", "Grant Writing", "Publication", "Data Analysis"],
    commonTasks: ["Conducting experiments", "Writing papers", "Peer review"],
    growthPotential: "Medium",
    difficultyLevel: "High",
    learningCurve: "High",
    possibleChallenges: ["Funding uncertainty", "Long feedback loops"],
  },
  {
    id: "edtech-product-manager",
    title: "EdTech PM",
    cluster: "Education",
    requiredTraits: { empathy: 8, structuredThinking: 8, communication: 8, curiosity: 7 },
    preferredWorkStyle: "Building technology to solve educational problems",
    fulfillingSkills: ["Product Strategy", "User Research", "Educational Standards", "Roadmapping"],
    commonTasks: ["Defining features", "Researching learners", "Prioritizing work"],
    growthPotential: "High",
    difficultyLevel: "Medium",
    learningCurve: "Medium",
    possibleChallenges: ["Fragmented market", "Slow adoption cycles"],
  },
];
